-- MySQL Script generated by MySQL Workbench
-- Thu Nov 26 16:51:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema register
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `register` ;

-- -----------------------------------------------------
-- Schema register
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `register` DEFAULT CHARACTER SET utf8 ;
USE `register` ;

-- -----------------------------------------------------
-- Table `register`.`columns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `register`.`columns` ;

CREATE TABLE IF NOT EXISTS `register`.`columns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NULL,
  `color` VARCHAR(45) NOT NULL,
  `column_index` INT NOT NULL,
  `is_category` TINYINT NOT NULL,
  `letter` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `register`.`columns` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_UNIQUE` ON `register`.`columns` (`name` ASC) VISIBLE;

CREATE UNIQUE INDEX `column_id_UNIQUE` ON `register`.`columns` (`column_index` ASC) VISIBLE;

CREATE UNIQUE INDEX `letter_UNIQUE` ON `register`.`columns` (`letter` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `register`.`merchants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `register`.`merchants` ;

CREATE TABLE IF NOT EXISTS `register`.`merchants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `bank_name` VARCHAR(60) NOT NULL,
  `column_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `column_id_fk`
    FOREIGN KEY (`column_id`)
    REFERENCES `register`.`columns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `register`.`merchants` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `bank_name_UNIQUE` ON `register`.`merchants` (`bank_name` ASC) VISIBLE;

CREATE INDEX `column_id_fk_idx` ON `register`.`merchants` (`column_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
